@extends('layouts.app-master')
<style>
    .kenburns-top {
        -webkit-animation: kenburns-top 5s ease-out infinite both;
        animation: kenburns-top 5s ease-out infinite both;
    }
    /* ----------------------------------------------
 * Generated by Animista on 2022-1-31 18:16:21
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
     * ----------------------------------------
     * animation kenburns-top
     * ----------------------------------------
     */
    @-webkit-keyframes kenburns-top {
        0% {
            -webkit-transform: scale(1) translateY(0);
            transform: scale(1) translateY(0);
            -webkit-transform-origin: 50% 16%;
            transform-origin: 50% 16%;
        }
        100% {
            -webkit-transform: scale(1.25) translateY(-15px);
            transform: scale(1.25) translateY(-15px);
            -webkit-transform-origin: top;
            transform-origin: top;
        }
    }
    @keyframes kenburns-top {
        0% {
            -webkit-transform: scale(1) translateY(0);
            transform: scale(1) translateY(0);
            -webkit-transform-origin: 50% 16%;
            transform-origin: 50% 16%;
        }
        100% {
            -webkit-transform: scale(1.25) translateY(-15px);
            transform: scale(1.25) translateY(-15px);
            -webkit-transform-origin: top;
            transform-origin: top;
        }
    }

</style>
@section('content')
    <img src="{{asset("logo.jpg")}}" class="anim-object active" id="image-large-object" style="animation: 5s ease-out 0s infinite normal both running kenburns-top;"></img>
@endsection
