<style>
       .text-pop-up-top {
        -webkit-animation: text-pop-up-top 1.5s cubic-bezier(0.785, 0.135, 0.150, 0.860) infinite alternate both;
        animation: text-pop-up-top 1.5s cubic-bezier(0.785, 0.135, 0.150, 0.860) infinite alternate both;
    }
    /* ----------------------------------------------
 * Generated by Animista on 2022-1-24 23:52:37
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

    /**
     * ----------------------------------------
     * animation text-pop-up-top
     * ----------------------------------------
     */
    @-webkit-keyframes text-pop-up-top {
        0% {
            -webkit-transform: translateY(0);
            transform: translateY(0);
            -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
            text-shadow: none;
        }
        100% {
            -webkit-transform: translateY(-50px);
            transform: translateY(-50px);
            -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
            text-shadow: 0 1px 0 #cccccc, 0 2px 0 #cccccc, 0 3px 0 #cccccc, 0 4px 0 #cccccc, 0 5px 0 #cccccc, 0 6px 0 #cccccc, 0 7px 0 #cccccc, 0 8px 0 #cccccc, 0 9px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.3);
        }
    }
    @keyframes text-pop-up-top {
        50% {
            -webkit-transform: translateY(0);
            transform: translateY(15px);
            -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
            text-shadow: none;
        }
        100% {
            -webkit-transform: translateY(-50px);
            transform: translateY(-15px);
            -webkit-transform-origin: 50% 50%;
            transform-origin: 50% 50%;
            text-shadow: 0 1px 0 #0dcaf0, 0 2px 0 #ffcd39, 0 3px 0 #6c757d, 0 4px 0 #eeeeee, 0 5px 0 #9561e2, 0 6px 0 #cccccc, 0 7px 0 #cccccc, 0 8px 0 #cccccc, 0 9px 0 #cccccc, 0 50px 30px rgba(0, 0, 0, 0.3);
        }
    }

</style>
<nav class="navbar navbar-expand-lg navbar-light " style="background:#424B5C ; !important;">

    <div class="container-fluid">
        <a href="{{route('out.home')}}"><img class="rotate" src="{{asset("logo.jpg")}}" style="width: 90px; margin-right: 5px"></a>
        <label class="text-pop-up-top" style="color: #eeeeee">News Gathering </label>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active text-white"  href="{{route('out.home')}}">Home</a>
                </li>

                @auth
                <li class="nav-item">
                    <a class="nav-link text-white" href="{{route('out.setting')}}">Setting</a>
                </li>
                @endauth
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle text-white"  href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Resources
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @foreach($resources as $resource)
                            <li><a class="dropdown-item" href="{{ route('resources.show.out', ['resource' => $resource->id]) }}">{{$resource->name}}</a></li>
                        @endforeach
                    </ul>
            </ul>
            @guest
                <a href="{{ route('login.out') }}#login" class="btn text-white float-md-end" style=" margin: 2px ;background-color: #A6AEBB">login</a>
                <a href="{{ route('login.out') }}" class="btn text-white float-md-end" style=" margin: 2px ;background-color: #A6AEBB">Sign Up</a>
            @else
                <form id="formout"  id="logout-form" action="{{ route('logout') }}" method="POST" class="float-md-end">
                    @csrf
                    @auth
                        <span class="text-info">{{auth()->user()->name}}&nbsp;&nbsp;({{ isset(auth()->user()->roles[0]['name']) ? auth()->user()->roles[0]['name'] : "Unknown"}})&nbsp;</span>
                    <button form="formout" type="submit" class="btn text-white float-md-end" style=" margin: 2px ;background-color: #c5d7f2">Logout</button>
                </form>
            @endauth
            @endguest
        </div>
    </div>
</nav>
<script>
    function rotateImage() {
        var img = document.getElementById('myimage');
        img.style.transform = 'rotate(90deg)';
    }
</script>
